import {
    ApisDefinition
} from 'nextgen-front-lib/modules/request'
export type Definitions = ApisDefinition <
    /* tslint:disable */
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    /**
     * Main
     * @see https://nextgen-travel.github.io/apis-doc/?target=genius-cart-app.yaml
     */
    {
        /**
         * [測試還有沒有活著用的] - 測試還有沒有活著用的
         */
        "get@hello": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@sliders": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@payments": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    name: string;
                    /**
                     * no description
                     */
                    title: string;
                    /**
                     * no description
                     */
                    subtitle: string;
                    /**
                     * no description
                     */
                    type: "manual" | "automatic";
                } [];
            };
            contentType: null;
        };
        /**
         * [取得限時活動資訊] - 取得限時活動資訊
         */
        "get@deal-of-the-day": {
            body: null;
            query: null;
            response: {
                /**
                 * 活動標題
                 * @example undefined
                 */
                deal_title: string;
                /**
                 * 活動細節
                 * @example undefined
                 */
                deal_details: string;
                /**
                 * 活動結束時間 yyyy-mm-dd Thh:mm:ss
                 * @example 2022-07-28 T00:00:00
                 */
                deal_time: string;
                /**
                 * 活動背景圖片url
                 * @example undefined
                 */
                deal_background: string;
            };
            contentType: null;
        };
        /**
         * [取得系統設定資訊] - 取得系統設定資訊
         */
        "get@general": {
            body: null;
            query: null;
            response: {
                /**
                 * 網站logo url
                 * @example undefined
                 */
                logo: string;
                /**
                 * 網站名稱
                 * @example undefined
                 */
                title: string;
                /**
                 * 網站顏色
                 * @example undefined
                 */
                colors: string;
            };
            contentType: null;
        };
        /**
         * [取得包裝方式] - 取得包裝方式
         */
        "get@packages": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 包裝名稱
                     * @example undefined
                     */
                    title: string;
                    /**
                     * 子標題
                     * @example undefined
                     */
                    subtitle: string;
                    /**
                     * 價格
                     * @example undefined
                     */
                    price: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得運送方式] - 取得運送方式
         */
        "get@shippings": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 運送方式名稱
                     * @example undefined
                     */
                    title: string;
                    /**
                     * 子標題（所需時間）
                     * @example undefined
                     */
                    subtitle: string;
                    /**
                     * 價格
                     * @example undefined
                     */
                    price: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得幣別及幣值資料（以港幣為基準）] - 取得幣別及幣值資料（以港幣為基準）
         */
        "get@currency": {
            body: null;
            query: null;
            response: {
                /**
                 * 幣別
                 * @example undefined
                 */
                currency_sign: string;
                /**
                 * 幣值（以港幣為基準）
                 * @example undefined
                 */
                currency_value: number;
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@countries": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    name: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@countries/:countryId/states": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@countries/tax/:countryId": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 該國家稅率
                     * @example undefined
                     */
                    tax: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得產品第一層類別] - 取得產品第一層類別
         */
        "get@categories": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                    /**
                     * 類別圖片url
                     * @example undefined
                     */
                    photo: string;
                    /**
                     * 類別圖片url
                     * @example undefined
                     */
                    image: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得特定第一層產品類別] - 取得特定第一層產品類別
         */
        "get@categories/:category": {
            body: null;
            query: null;
            response: {
                /**
                 * 類別ID
                 * @example undefined
                 */
                id: number;
                /**
                 * 類別名稱
                 * @example undefined
                 */
                name: string;
                /**
                 * 類別圖片url
                 * @example undefined
                 */
                photo: string;
                /**
                 * 類別圖片url
                 * @example undefined
                 */
                image: string;
            };
            contentType: null;
        };
        /**
         * [取得特定第一層產品類別的所有子類別（第二層）] - 取得特定第一層產品類別的所有子類別（第二層）
         */
        "get@categories/:category/subs": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                    /**
                     * 類別圖片url
                     * @example undefined
                     */
                    photo: string;
                    /**
                     * 類別圖片url
                     * @example undefined
                     */
                    image: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得特定第一層產品類別下的特定子類別（第二層）] - 取得特定第一層產品類別底下的特定子類別（第二層）
         */
        "get@categories/:category/subs/:sub": {
            body: null;
            query: null;
            response: {
                /**
                 * 類別ID
                 * @example undefined
                 */
                id: number;
                /**
                 * 類別名稱
                 * @example undefined
                 */
                name: string;
                /**
                 * 類別圖片url
                 * @example undefined
                 */
                photo: string;
                /**
                 * 類別圖片url
                 * @example undefined
                 */
                image: string;
            };
            contentType: null;
        };
        /**
         * [取得特定第二層類別的所有子類別（第三層）] - 取得特定第二層類別的所有子類別（第三層）
         */
        "get@subcategories/:subcategory_id/children": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                    /**
                     * 當前類別ID
                     * @example undefined
                     */
                    subcategory_id: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得特定第二層類別的特定子類別（第三層）] - 取得特定第二層類別的特定子類別（第三層）
         */
        "get@subcategories/:subcategory_id/children/:child": {
            body: null;
            query: null;
            response: {
                /**
                 * 類別ID
                 * @example undefined
                 */
                id: number;
                /**
                 * 上層類別ID
                 * @example undefined
                 */
                subcategory_id: number;
                /**
                 * 類別名稱
                 * @example undefined
                 */
                name: string;
            };
            contentType: null;
        };
        /**
         * [取得特定第三層類別的所有子類別（第四層）] - 取得特定第三層類別的所有子類別（第四層）
         */
        "get@childcategories/:childcategory_id/fourths": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得特定第三層類別的特定子類別（第四層）] - 取得特定第三層類別的特定子類別（第四層）
         */
        "get@childcategories/:childcategory_id/fourths/:fourth": {
            body: null;
            query: null;
            response: {
                /**
                 * 類別ID
                 * @example undefined
                 */
                id: number;
                /**
                 * 上層類別ID
                 * @example undefined
                 */
                childcategory_id: number;
                /**
                 * 類別名稱
                 * @example undefined
                 */
                name: string;
            };
            contentType: null;
        };
        /**
         * [取得特定第四層類別的所有子類別（第五層）] - 取得特定第四層類別的所有子類別（第五層）
         */
        "get@fourthcategories/:fourthcategory_id/fifths": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 類別ID
                     * @example undefined
                     */
                    id: number;
                    /**
                     * 類別名稱
                     * @example undefined
                     */
                    name: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得特定第四層類別的特定子類別（第五層）] - 取得特定第四層類別的特定子類別（第五層）
         */
        "get@fourthcategories/:fourthcategory_id/fifths/:fifth": {
            body: null;
            query: null;
            response: {
                /**
                 * 類別ID
                 * @example undefined
                 */
                id: number;
                /**
                 * 上層類別ID
                 * @example undefined
                 */
                fourthcategory_id: number;
                /**
                 * 類別圖片url
                 * @example undefined
                 */
                name: string;
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@products": {
            body: null;
            query: {
                /**
                 * no description
                 */
                hot ? : number;
                /**
                 * no description
                 */
                new ? : number;
                /**
                 * no description
                 */
                sale ? : number;
                /**
                 * no description
                 */
                category ? : number;
                /**
                 * no description
                 */
                subcategory ? : number;
                /**
                 * no description
                 */
                childcategory ? : number;
                /**
                 * no description
                 */
                fourthcategory ? : number;
                /**
                 * no description
                 */
                fifthcategory ? : number;
                /**
                 * no description
                 */
                best_seller ? : number;
                /**
                 * no description
                 */
                best ? : number;
                /**
                 * no description
                 */
                featured ? : number;
                /**
                 * no description
                 */
                trending ? : number;
                /**
                 * no description
                 */
                in ? : string;
                /**
                 * no description
                 */
                keyword ? : string;
                /**
                 * no description
                 */
                min_price ? : number;
                /**
                 * no description
                 */
                max_price ? : number;
                /**
                 * no description
                 */
                order_by ? : string;
                /**
                 * no description
                 */
                sort ? : string;
            };
            response: {
                data: unknown[];
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@products/:id": {
            body: null;
            query: null;
            response: {
                data: unknown[];
            };
            contentType: null;
        };
        /**
         * [取得該產品的多個規格內容] - 取得該產品的多個規格內容
         */
        "get@products/:id/skus": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 該規格的sku碼
                     * @example undefined
                     */
                    sku: string;
                    /**
                     * 特定規格
                     * @example undefined
                     */
                    size: string;
                    /**
                     * 該規格價格
                     * @example undefined
                     */
                    price: number;
                    /**
                     * 該規格顏色
                     * @example undefined
                     */
                    color: string;
                    /**
                     * 該規格庫存
                     * @example undefined
                     */
                    stock: string;
                    /**
                     * 該規格定價
                     * @example undefined
                     */
                    previous_price: number;
                    /**
                     * 該規格折扣
                     * @example undefined
                     */
                    discount: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@products/search-tags": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@products/search-tags": {
            body: {
                /**
                 * 搜尋關鍵字
                 * @example airpod
                 */
                keyword: string;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@login": {
            body: {
                /**
                 * 帳號信箱
                 * @example aaa@abc.com
                 */
                email: string;
                /**
                 * 密碼
                 * @example 12345
                 */
                password: string;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@register": {
            body: {
                /**
                 * 用戶名稱
                 * @example Jin
                 */
                name: string;
                /**
                 * 帳號信箱
                 * @example aaa@abc.com
                 */
                email: string;
                /**
                 * 密碼
                 * @example 12345
                 */
                password: string;
                /**
                 * 密碼確認
                 * @example 12345
                 */
                password_confirmation: string;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@client": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [取得收藏商品] - 取得收藏商品
         */
        "get@client/wishlist": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 產品ID
                     * @example 1
                     */
                    product_id: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@client/wishlist": {
            body: {
                /**
                 * 產品ID
                 * @example 123
                 */
                product_id: number;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "delete@client/wishlist/:wishId": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@client/orders": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@client/dashboard": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 錢包餘額
                     * @example 100
                     */
                    balance: number;
                    /**
                     * 會員獎勵點數
                     * @example 60
                     */
                    reward: number;
                    /**
                     * 二次行銷獎勵
                     * @example 150
                     */
                    affilate_income: number;
                };
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@client/dashboard/orders": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 訂單編號
                     * @example 2CiO1662602659
                     */
                    order_number: string;
                    /**
                     * 訂單金額
                     * @example 140
                     */
                    pay_amount: number;
                    /**
                     * 訂單狀態
                     * @example pending
                     */
                    payment_status: string;
                    /**
                     * 訂單成立時間
                     * @example 2022-09-08
                     */
                    created_at: string;
                } [];
                meta: {
                    /**
                     * 當前頁面
                     * @example 1
                     */
                    current_page: number;
                    /**
                     * 每頁數量
                     * @example 10
                     */
                    per_page: number;
                    /**
                     * 訂單總數
                     * @example 18
                     */
                    total: number;
                };
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@client/dashboard/orders/pending": {
            body: null;
            query: null;
            response: {
                /**
                 * 未付款訂單數量
                 * @example 2
                 */
                totalPending: number;
            };
            contentType: null;
        };
        /**
         * [取得使用者當前獎勵點數及最大可轉換金額以及轉換公式資訊] - 取得使用者當前獎勵點數及最大可轉換金額以及轉換公式資訊
         */
        "get@client/rewards": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 會員獎勵點數
                     * @example 1000
                     */
                    user_reward_point: number;
                    /**
                     * 轉換公式點數
                     * @example 20
                     */
                    reward_point: number;
                    /**
                     * 轉換公式金額
                     * @example 1
                     */
                    reward_dollar: number;
                    /**
                     * 最多可兌換的金額（會員獎勵點數＊上轉換公式）
                     * @example 50
                     */
                    max_reward: number;
                    /**
                     * 轉換公式 (轉換公式金額／轉換公式點數)
                     * @example 0.5
                     */
                    reward_formula: number;
                };
            };
            contentType: null;
        };
        /**
         * [取得使用者過往獎勵點數轉換紀錄] - 取得使用者過往獎勵點數轉換紀錄
         */
        "get@client/rewards/transactions": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 用來轉換的獎勵點數
                     * @example undefined
                     */
                    reward_point: number;
                    /**
                     * 轉換後得到的金額
                     * @example undefined
                     */
                    reward_dollar: number;
                    /**
                     * 轉換時間
                     * @example undefined
                     */
                    created_at: string;
                } [];
            };
            contentType: null;
        };
        /**
         * [轉換點數計算] - 轉換點數計算
         */
        "post@client/rewards/convert": {
            body: {
                /**
                 * 轉換使用的點數
                 * @example 50
                 */
                reward_point: number;
            };
            query: null;
            response: {
                data: {
                    /**
                     * 用來轉換的獎勵點數
                     * @example undefined
                     */
                    reward_point: number;
                };
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@cart/compute": {
            body: {
                items: unknown[];
                /**
                 * 優惠券
                 * @example undefined
                 */
                coupon: number;
                /**
                 * 錢包
                 * @example 10
                 */
                deposits: number;
                /**
                 * 運送方式（快速或是一般...)
                 * @example 1
                 */
                shippings: number;
                /**
                 * 包裝方式（豪華包裝或是一般...)
                 * @example 1
                 */
                packages: number;
                /**
                 * 自取點ID
                 * @example undefined
                 */
                pickups: number;
                /**
                 * 國家ID（計算稅率用）
                 * @example undefined
                 */
                country: number;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@cart/checkout": {
            body: {
                /**
                 * 購買人
                 * @example 老高
                 */
                customer_name: string;
                /**
                 * 帳單區域
                 * @example 215
                 */
                customer_country: number;
                /**
                 * 帳單電話
                 * @example 0900123123
                 */
                customer_phone: string;
                /**
                 * 帳單地址
                 * @example 九龍
                 */
                customer_address: string;
                /**
                 * 帳單區碼
                 * @example 123
                 */
                customer_zip: string;
                /**
                 * 帳單郵件
                 * @example zzz@nextgen.com
                 */
                customer_email: string;
                /**
                 * 帳單州
                 * @example 47
                 */
                customer_state: number;
                /**
                 * 取貨人
                 * @example 茉莉
                 */
                shipping_name: string;
                /**
                 * 送達城市
                 * @example 215
                 */
                shipping_country: number;
                /**
                 * 送達電話
                 * @example 0900123123
                 */
                shipping_phone: string;
                /**
                 * 送達地址
                 * @example 新界
                 */
                shipping_address: string;
                /**
                 * 送達區碼
                 * @example 123
                 */
                shipping_zip: string;
                /**
                 * 送達郵件
                 * @example aaa@nextgen.hk.com
                 */
                shipping_email: string;
                /**
                 * 送達州
                 * @example 47
                 */
                shipping_state: number;
                /**
                 * 自取點
                 * @example 0
                 */
                pickups: number;
                /**
                 * 包裝方式
                 * @example 1
                 */
                packages: number;
                /**
                 * 送達方式（快速，一般....)
                 * @example 1
                 */
                shippings: number;
                /**
                 * 付款方式 (現金，信用卡等等，目前只有現金/1)
                 * @example 1
                 */
                payment_method: number;
                /**
                 * 收件人資料 1 同訂購人  / 2 新增收件人資料
                 * @example 1
                 */
                recipient: number;
                /**
                 * 外送(1)或是自取點(2)
                 * @example 1
                 */
                shippingType: 1 | 2;
                /**
                 * 送達地址是否同顧客地址(0 false /1 true)
                 * @example 0
                 */
                shipping_different: 0 | 1;
                items: unknown[];
            };
            query: null;
            response: {
                data: {
                    /**
                     * 訂單ID
                     * @example undefined
                     */
                    order_id: number;
                    /**
                     * 訂單號碼
                     * @example undefined
                     */
                    order_number: string;
                };
            };
            contentType: null;
        };
        /**
         * [取得免運費資料] - 取得免運費資料
         */
        "get@cart/checkout-info": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 基礎運費
                     * @example 50
                     */
                    shipping_fee: number;
                    /**
                     * 免運費門檻
                     * @example 200
                     */
                    shipping_free: number;
                };
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@orders/:orderNumber": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "get@orders/:orderNumber/products": {
            body: null;
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@orders/:orderNumber/pay/:paymentName": {
            body: {
                /**
                 * 幣別
                 * @example hkd
                 */
                currency: string;
            };
            query: null;
            response: null;
            contentType: null;
        };
        /**
         * [取得自取點] - 取得特定國家下的自取點
         */
        "get@pickups/:countryId": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 自取點ID
                     * @example 1
                     */
                    id: number;
                    /**
                     * 自取點位置
                     * @example undefined
                     */
                    location: string;
                    /**
                     * 自取點詳細地址
                     * @example undefined
                     */
                    address: string;
                    /**
                     * 自取點相關內容
                     * @example undefined
                     */
                    note: string;
                    /**
                     * 自取點費用
                     * @example 10
                     */
                    cost: number;
                } [];
            };
            contentType: null;
        };
        /**
         * [取得該優惠卷] - 取得特定國家下的自取點
         */
        "get@coupons/price/:couponCode": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * 優惠卷類別 (1表示現金折抵 0表示百分比折抵)
                     * @example 1
                     */
                    type: number;
                    /**
                     * 優惠卷折扣金額or百分比
                     * @example undefined
                     */
                    price: number;
                };
            };
            contentType: null;
        };
    }

    >