import {
    ApisDefinition
} from 'nextgen-front-lib/modules/request'
export type Definitions = ApisDefinition <
    /* tslint:disable */
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    /**
     * Main
     * @see https://nextgen-travel.github.io/apis-doc/?target=main.yaml
     */
    {
        /**
         * [這裡放簡易說明] - 這裡放複雜說明
         */
        "get@users/:user": {
            body: null;
            query: null;
            response: {
                /**
                 * 使用者名稱
                 * @example 小明
                 */
                name: string;
            };
            contentType: null;
        };
        /**
         * [no summary] - no description
         */
        "post@users/:user": {
            body: {
                /**
                 * 標題提
                 * @example hi...
                 */
                title: string;
            };
            query: null;
            response: null;
            contentType: null;
        };
    }

    >