import {
    ApisDefinition
} from 'nextgen-front-lib/modules/request'
export type Definitions = ApisDefinition <
    /* tslint:disable */
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    /**
     * 配藥系統
     * @see https://nextgen-travel.github.io/apis-doc/?target=medicine-private.yaml
     */
    {
        /**
         * [員工登錄帳號] - no description
         */
        "post@users-permissions/auth/login": {
            body: {
                /**
                 * email
                 * @example pharmacist@nextgen.com.hk
                 */
                email: string;
                /**
                 * 密碼
                 * @example nextgen123
                 */
                password: string;
            };
            query: null;
            response: {
                /**
                 * no description
                 */
                jwt: string;
                user: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    username: string;
                    /**
                     * no description
                     */
                    email: string;
                    /**
                     * no description
                     */
                    provider: string;
                    /**
                     * no description
                     */
                    confirmed: boolean;
                    /**
                     * no description
                     */
                    blocked: boolean;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    memo: string;
                    /**
                     * no description
                     */
                    level: string;
                    /**
                     * no description
                     */
                    startedAt: string;
                    /**
                     * no description
                     */
                    finishedAt: string;
                    /**
                     * no description
                     */
                    isPharmacist: boolean;
                    store: {
                        /**
                         * no description
                         */
                        id: number;
                        /**
                         * no description
                         */
                        nanmeCn: string;
                        /**
                         * no description
                         */
                        ameEn: string;
                        /**
                         * no description
                         */
                        tel: string;
                        /**
                         * no description
                         */
                        address: string;
                        /**
                         * no description
                         */
                        district: string;
                        /**
                         * no description
                         */
                        rxNo: string;
                        /**
                         * no description
                         */
                        createdAt: string;
                        /**
                         * no description
                         */
                        updatedAt: string;
                        /**
                         * no description
                         */
                        publishedAt: string;
                    };
                };
            };
            contentType: null;
        };
        /**
         * [客人搜尋] - no description
         */
        "get@customers": {
            body: null;
            query: {
                /**
                 * no description
                 */
                expand: string;
                /**
                 * no description
                 */
                email: string;
                /**
                 * no description
                 */
                mobile: string;
                /**
                 * no description
                 */
                account_no: string;
            };
            response: {
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    uuid: string;
                    /**
                     * no description
                     */
                    gender: string;
                    /**
                     * no description
                     */
                    address: string;
                    /**
                     * no description
                     */
                    email: string;
                    /**
                     * no description
                     */
                    birthday: string;
                    /**
                     * no description
                     */
                    name: string;
                    /**
                     * no description
                     */
                    mobile: string;
                    /**
                     * no description
                     */
                    accountNo: string;
                    /**
                     * no description
                     */
                    drugTaboo: string;
                    store: {
                        /**
                         * no description
                         */
                        rxNo: string;
                        /**
                         * no description
                         */
                        nameCn: string;
                        /**
                         * no description
                         */
                        nameEn: string;
                        /**
                         * no description
                         */
                        district: string;
                    };
                } [];
                meta: {
                    /**
                     * no description
                     */
                    page: number;
                    /**
                     * no description
                     */
                    perPage: number;
                    /**
                     * no description
                     */
                    pageCount: number;
                    /**
                     * no description
                     */
                    totalCount: number;
                };
            };
            contentType: null;
        };
        /**
         * [新建客人] - no description
         */
        "post@customers": {
            body: null;
            query: null;
            response: {
                /**
                 * no description
                 */
                msg: string;
                data: {
                    /**
                     * no description
                     */
                    gender: string;
                    /**
                     * no description
                     */
                    address: string;
                    /**
                     * no description
                     */
                    email: string;
                    /**
                     * no description
                     */
                    birthday: string;
                    /**
                     * no description
                     */
                    name: string;
                    /**
                     * no description
                     */
                    mobile: string;
                    /**
                     * no description
                     */
                    accountNo: string;
                    /**
                     * no description
                     */
                    drugTaboo: string;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    uuid: string;
                };
            };
            contentType: null;
        };
        /**
         * [修改客人資訊] - no description
         */
        "put@customers/:uuid": {
            body: null;
            query: null;
            response: {
                /**
                 * no description
                 */
                msg: string;
                data: {
                    /**
                     * no description
                     */
                    gender: string;
                    /**
                     * no description
                     */
                    address: string;
                    /**
                     * no description
                     */
                    email: string;
                    /**
                     * no description
                     */
                    birthday: string;
                    /**
                     * no description
                     */
                    name: string;
                    /**
                     * no description
                     */
                    mobile: string;
                    /**
                     * no description
                     */
                    accountNo: string;
                    /**
                     * no description
                     */
                    drugTaboo: string;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    uuid: string;
                };
            };
            contentType: null;
        };
        /**
         * [新建訂單] - no description
         */
        "post@orders": {
            body: null;
            query: null;
            response: {
                /**
                 * no description
                 */
                msg: string;
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    signAt: string;
                    /**
                     * no description
                     */
                    doctorName: string;
                    prescriptionSignMessage: {};
                    /**
                     * no description
                     */
                    hospitalName: string;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    orderNo: string;
                };
            };
            contentType: null;
        };
        /**
         * [修改訂單] - no description
         */
        "put@orders/:orderNo": {
            body: null;
            query: null;
            response: {
                /**
                 * no description
                 */
                msg: string;
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    signAt: string;
                    /**
                     * no description
                     */
                    doctorName: string;
                    prescriptionSignMessage: {};
                    /**
                     * no description
                     */
                    hospitalName: string;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    orderNo: string;
                };
            };
            contentType: null;
        };
    }

    >