import {
    ApisDefinition
} from 'nextgen-front-lib/modules/request'
export type Definitions = ApisDefinition <
    /* tslint:disable */
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    /**
     * 配藥系統
     * @see https://nextgen-travel.github.io/apis-doc/?target=medicine-public.yaml
     */
    {
        /**
         * [員工登錄帳號] - no description
         */
        "post@users-permissions/auth/login": {
            body: {
                /**
                 * email
                 * @example pharmacist@nextgen.com.hk
                 */
                email: string;
                /**
                 * 密碼
                 * @example nextgen123
                 */
                password: string;
            };
            query: null;
            response: {
                /**
                 * no description
                 */
                jwt: string;
                user: {
                    /**
                     * no description
                     */
                    id: number;
                    /**
                     * no description
                     */
                    username: string;
                    /**
                     * no description
                     */
                    email: string;
                    /**
                     * no description
                     */
                    provider: string;
                    /**
                     * no description
                     */
                    confirmed: boolean;
                    /**
                     * no description
                     */
                    blocked: boolean;
                    /**
                     * no description
                     */
                    createdAt: string;
                    /**
                     * no description
                     */
                    updatedAt: string;
                    /**
                     * no description
                     */
                    memo: string;
                    /**
                     * no description
                     */
                    level: string;
                    /**
                     * no description
                     */
                    startedAt: string;
                    /**
                     * no description
                     */
                    finishedAt: string;
                    /**
                     * no description
                     */
                    isPharmacist: boolean;
                    store: {
                        /**
                         * no description
                         */
                        id: number;
                        /**
                         * no description
                         */
                        NameCn: string;
                        /**
                         * no description
                         */
                        NameEn: string;
                        /**
                         * no description
                         */
                        tel: string;
                        /**
                         * no description
                         */
                        address: string;
                        /**
                         * no description
                         */
                        district: string;
                        /**
                         * no description
                         */
                        rx_no: string;
                        /**
                         * no description
                         */
                        createdAt: string;
                        /**
                         * no description
                         */
                        updatedAt: string;
                        /**
                         * no description
                         */
                        publishedAt: string;
                    };
                };
            };
            contentType: null;
        };
        /**
         * [獲取藥物使用方法] - no description
         */
        "get@dosage-forms": {
            body: null;
            query: null;
            response: {
                data: {
                    /**
                     * no description
                     */
                    id: number;
                    attributes: {
                        /**
                         * no description
                         */
                        key: string;
                        /**
                         * no description
                         */
                        createdAt: string;
                        /**
                         * no description
                         */
                        updatedAt: string;
                        /**
                         * no description
                         */
                        publishedAt: string;
                    };
                } [];
                meta: {
                    pagination: {
                        /**
                         * no description
                         */
                        page: number;
                        /**
                         * no description
                         */
                        pageSize: number;
                        /**
                         * no description
                         */
                        pageCount: number;
                        /**
                         * no description
                         */
                        total: number;
                    };
                };
            };
            contentType: null;
        };
    }

    >