openapi: 3.0.1

info:
  title: ERP 預約系統
  version: 1.0.0
  description: ERP 預約系統相關 API

tags:
  - name: booking
    description: 新版POS相關API

# 這裡可以選擇網域
servers:
  - url: http://localhost:8000/project/public/api/sync/

components:
  # 定義一些 auth 認證的 token
  securitySchemes:
    token:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的token
  # 定義一些通用參數避免繁複定義
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:

  /booking/new:
    post:
      tags:
        - booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                business_id:
                  type: integer
                  description: 總店ID
                  example: 1
                location_id:
                  type: integer
                  description: 分店ID
                  example: 1
                contact_id:
                  type: integer
                  description: 顧客ID
                  example: 40
                contact_name:
                  type: string
                  description: 顧客姓名
                  example: 王小明
                contact_mobile:
                  type: string
                  description: 顧客手機
                  example: 0912654987
                contact_email:
                  type: string
                  description: 顧客 email
                  example: "wangming@nextgen.com.hk"
                contact_uuid:
                  type: string
                  description: 顧客 UUID
                  example: "dsgcydsgv-2t78dtcg8-dshcsd89y"
                correspondent:
                  type: integer
                  description: 接線生ID
                  example: 1
                res_table_id:
                  type: integer
                  description: 餐桌ID
                  example: 3
                res_waiter_id:
                  type: integer
                  description: 服務生ID
                  example: 5
                booking_start:
                  type: string
                  description: 預約開始時間
                  example: "01/24/2023 15:40"
                booking_end:
                  type: string
                  description: 預約結束時間
                  example: "01/25/2023 15:45"
                booking_note:
                  type: string
                  description: 預約備註
                  example: "海景第一排"
      responses:
        '200':
          description: 成功
  /booking/service-staff:
    get:
      summary: 取得服務人員列表
      description: 取得服務人員
      # 分類
      tags:
        - booking
      responses:
        '200':
          description: 成功
  /booking/service-staff/{id}:
    get:
      summary: 服務人員詳細資訊及可預約場次
      description: 取得指定服務人員詳細資訊及可預約場次
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      # 分類
      tags:
        - booking
      responses:
        '200':
          description: 成功
