openapi: 3.0.1

info:
  title: 醫藥淘
  version: 1.0.0
  description: ERP 提供給 醫藥淘庫存查詢用

servers:
  - url: http://erp-dev.cloudsatlas.com.hk/api
  # sample : http://erp-dev.cloudsatlas.com.hk/api/v1/eyt/products

components:
  parameters:
    page:
      in: query
      name: pagination[page]
      schema:
        type: number
      required: true
      example: 1
    prepage:
      in: query
      name: pagination[pageSize]
      schema:
        type: number
      required: true
      example: 100
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'
  schemas:
    ProductsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                description: 藥品 id
              sku:
                type: string
                description: 藥品 SKU
              name:
                type: string
                description: 藥品名稱
              qty_available:
                type: number
                description: 庫存數量
              alert_quantity:
                type: string
                description: 庫存警告數量
              default_sell_price:
                type: string
                description: 售價
              product_custom_field1:
                type: string
                description: 藥品證號
              product_custom_field2:
                type: string
                description: 藥品英文名稱
              product_custom_field3:
                type: string
                description: 藥廠
              product_custom_field4:
                type: string
                description: 藥品主成份
    SingleProductResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              description: 藥品 id
            sku:
              type: string
              description: 藥品 SKU
            name:
              type: string
              description: 藥品名稱
            unit_id:
              type: integer
              description: 單位ID
            qty_available:
              type: number
              description: 庫存總數量
            alert_quantity:
              type: string
              description: 庫存警告數量
            unit_short_name:
              type: string
              description: 單位簡稱
            product_custom_field1:
              type: string
              description: 藥品證號
            product_custom_field2:
              type: string
              description: 藥品英文名稱
            product_custom_field3:
              type: string
              description: 藥廠
            product_custom_field4:
              type: string
              description: 藥品主成份
            stock:
              type: array
              items:
                type: object
                properties:
                  variation_id:
                    type: integer
                    description: 規格ID
                  unit_name:
                    type: string
                    description: 單位名稱
                  default_sell_price:
                    type: string
                    description: 售價(不含稅)
                  qty_available:
                    type: string
                    description: 庫存數量

paths:

  # ====================
  #
  # products
  #
  /v1/eyt/products:
    get:
      summary: 產品清單
      description: "取得產品清單"
      tags:
        - products
      # security:
      #   - bearerAuth: []
      parameters:
        - in: query
          name: location_id
          schema:
            type: integer
          description: The ID of location
          required: true
        - in: query
          name: keyword
          schema:
            type: string
          description: The keyword for search products
        - in: query
          name: per_page
          schema:
            type: integer
          description: 每頁筆數
        - in: query
          name: page
          schema:
            type: integer
          description: 頁碼
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
              example:
                data:
                - id: 1
                  sku: SKU123
                  name: 眼藥水
                  qty_available: 200
                  alert_quantity: 10
                  default_sell_price: 125.000
                  product_custom_field1: HK-58956
                  product_custom_field2: S.T. NATURAL TEARS EYE DROPS
                  product_custom_field3: BIO
                  product_custom_field4: Vintamic C
                - id: 2
                  sku: SKU223
                  name: 暈船藥
                  qty_available: 250
                  alert_quantity: 15
                  default_sell_price: 110.000
                  product_custom_field1: HK-68741
                  product_custom_field2: S.T. NATURAL TEARS EYE DROPS
                  product_custom_field3: BIO
                  product_custom_field4: Vintamic C
                links:
                  type: object
                  properties:
                    first:
                      type: string
                    last:
                      type: string
                    prev:
                      type: string
                    next:
                      type: string
                meta:
                  type: object
                  properties:
                    current_page:
                      type: number
                    from:
                      type: number
                    last_page:
                      type: number
                    path:
                      type: string
                    per_page:
                      type: number
                    to:
                      type: number
                    total:
                      type: number
  /v1/eyt/products/{id}:
    get:
      summary: '取得單一產品'
      description: 取得單一產品詳細資訊
      tags:
        - products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
        - name: location_id
          in: query
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProductResponse'
