openapi: 3.0.1

info:
  title: 醫藥淘
  version: 1.0.0

servers:
  - url: http://localhost:1339/api/
  - url: https://e-drugsearch.com.hk/api/

components:
  parameters:
    page:
      in: query
      name: pagination[page]
      schema:
        type: number
      required: true
      example: 1
    prepage:
      in: query
      name: pagination[pageSize]
      schema:
        type: number
      required: true
      example: 100
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:

  # ====================
  #
  # Auth
  #


  # ====================
  #
  # posts
  #

  /posts:
    get:
      summary: 獲取文章列表
      tags:
        - posts
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        title:
                          type: string
                        content:
                          type: string
                        store:
                          type: string
                        type:
                          type: string
                        viewCount:
                          type: number
                        image:
                          type: string

    post:
      summary: 建立文章
      tags:
        - posts
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 文章標題
                content:
                  type: string
                  description: 文章內容
                store:
                  type: number
                  description: 該文章是屬於哪一個供應商，當前因無後台機制故先寫死
                  example: 1
                type:
                  type: string
                  example: 藥物新知
                  description: 文章類別
                locale:
                  type: string
                  enum: ['zh', 'en', 'zh-CN']
                  description: 文章語言，上面分別對應 繁體中文，英文，簡體中文
                image:
                  type: string
                  example: binary
                  description: 文章圖片 
                sort:
                  type: number        
                  description: 排序順序
                  example: 999     
                publishStart:
                  type: string
                  description: 預計上架時間（實際功能會到 phaseII 實作）
                publishEnd:
                  type: number
                  description: 預計下架時間（實際功能會到 phaseII 實作）

              required:
                - title
                - store
                - type
                - locale
                - image

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      title:
                        type: string
                      content:
                        type: string
                      store:
                        type: string
                      type:
                        type: string
                      sort:
                        type: number
                      viewCount:
                        type: number
                      isApproved:
                        type: boolean
                      isDeleted:
                        type: boolean
                      publishStart:
                        type: string
                      publishEnd:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      locale:
                        type: string
                      image:
                        type: string

        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  伺服器錯誤
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  建立失敗                              

  /posts/{id}:
    get:
      summary: 獲取指定文章
      tags:
        - posts
      parameters:
        - name: id
          in: path
          description: 文章id
          required: true
          example: 3
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  post:
                    type: object
                    properties:
                      title:
                        type: string
                      content:
                        type: string
                      store:
                        type: string
                      type:
                        type: string
                      viewCount:
                        type: number
                      image:
                        type: string

    # review
    put:
      summary: 更新指定文章
      tags:
        - posts
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: post id
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 文章標題
                content:
                  type: string
                  description: 文章內容
                store:
                  type: number
                  description: 該文章是屬於哪一個供應商，當前因無後台機制故先寫死
                  example: 1
                type:
                  type: string
                  example: 藥物新知
                  description: 文章類別
                locale:
                  type: string
                  enum: ['zh', 'en', 'zh-CN']
                  description: 文章語言，上面分別對應 繁體中文，英文，簡體中文
                image:
                  type: string
                  example: binary
                  description: 文章圖片 
                sort:
                  type: number        
                  description: 排序順序
                  example: 999     
                publishStart:
                  type: string
                  description: 預計上架時間（實際功能會到 phaseII 實作）
                publishEnd:
                  type: number
                  description: 預計下架時間（實際功能會到 phaseII 實作）

              required:
                - title
                - store
                - type
                - locale
                - image

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      title:
                        type: string
                      content:
                        type: string
                      store:
                        type: string
                      type:
                        type: string
                      sort:
                        type: number
                      viewCount:
                        type: number
                      isApproved:
                        type: boolean
                      isDeleted:
                        type: boolean
                      publishStart:
                        type: string
                      publishEnd:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      locale:
                        type: string
                      image:
                        type: string

        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  伺服器錯誤
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  建立失敗         

  # ====================
  #
  # stores
  #

  /stores/list:
    get:
      summary: 獲取商店的id及name
      tags:
        - stores
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string