openapi: 3.0.1

info:
  title: Main
  version: 1.0.0

servers:
  - url: http://localhost:8000/api/app

components:
  # 定義一些 auth 認證的 token
  securitySchemes:
    client:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的 token, Bearer xxx
  parameters:
    page:
      in: query
      name: page
      schema:
        type: number
      required: true
      example: 1
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:
  /hello:
    get:
      summary: 測試還有沒有活著用的
      description: 測試還有沒有活著用的
      tags:
        - hello
      responses:
        '200':
          description: 成功

  /sliders:
    get:
      responses:
        '200':
          description: 成功

  /payments:
    get:
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        title:
                          type: string
                        subtitle:
                          type: string
                        type:
                          type: string
                          enum:
                            - manual
                            - automatic
  /deal-of-the-day:
    get:
      summary: 取得限時活動資訊
      description: 取得限時活動資訊
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  deal_title:
                    type: string
                    description: 活動標題
                  deal_details:
                    type: string
                    description: 活動細節
                  deal_time:
                    type: string
                    description: 活動結束時間 yyyy-mm-dd Thh:mm:ss
                    example: '2022-07-28 T00:00:00'
                  deal_background:
                    type: string
                    description: 活動背景圖片url

  # ==================
  # countries
  # ==================

  /countries:
    get:
      tags:
        - country
      parameters:
        - in: path
          name: countryId
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string

  /countries/{countryId}/states:
    get:
      tags:
        - country
      parameters:
        - in: path
          name: countryId
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: 類別ID
                        name:
                          type: string
                          description: 類別名稱

  # ==================
  # categories
  # ==================

  /categories:
    get:
      summary: 取得產品類別
      description: 取得產品類別
      tags:
        - categories
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: 類別ID
                        name:
                          type: string
                          description: 類別名稱
                        photo:
                          type: string
                          description: 類別圖片url
                        image:
                          type: string
                          description: 類別圖片url

  /categories/{category}:
    get:
      summary: 取得特定產品類別
      description: 取得特定產品類別
      tags:
        - categories
      parameters:
        - in: path
          name: category
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: 類別ID
                  name:
                    type: string
                    description: 類別名稱
                  photo:
                    type: string
                    description: 類別圖片url
                  image:
                    type: string
                    description: 類別圖片url

  /categories/{category}/subs:
    get:
      summary: 取得該類別的子類別
      description: 取得該類別的子類別
      tags:
        - categories
      parameters:
        - in: path
          name: category
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功

  /categories/{category}/subs/{sub}:
    get:
      summary: 取得該類的子類別的單一類別
      description: 取得該類的子類別的單一類別
      tags:
        - categories
      parameters:
        - in: path
          name: category
          schema:
            type: number
          required: true
          example: 1
        - in: path
          name: sub
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功

  # ==================
  # products
  # ==================

  /products:
    get:
      tags:
        - products
      parameters:
        - in: query
          name: hot
          schema:
            type: number
          required: false
          allowEmptyValue: true
        - in: query
          name: sale
          schema:
            type: number
          required: false
        - in: query
          name: category
          schema:
            type: number
          required: false
        - in: query
          name: best_seller
          schema:
            type: number
          required: false
        - in: query
          name: featured
          schema:
            type: number
          required: false
        - in: query
          name: trending
          schema:
            type: number
          required: false
        - in: query
          name: in
          schema:
            type: string
          required: false
          allowEmptyValue: true
        #- $ref: '#/components/parameters/page'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array

  /products/{id}:
    get:
      tags:
        - products
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
          example: 1
      responses:
        '200':
          description: 成功
        '404':
          description: 查無資料

  # ==================
  # client
  # ==================

  /login:
    post:
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 帳號信箱
                  example: aaa@abc.com
                password:
                  type: string
                  description: 密碼
                  example: 12345
      responses:
        '200':
          description: 成功

  /client:
    get:
      tags:
        - user
      security:
        - client: []
      responses:
        '200':
          description: 成功

  /client/wishlist:
    get:
      summary: 取得收藏商品
      description: 取得收藏商品
      tags:
        - user
      security:
        - client: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: number
                          description: 產品ID
                          example: 1
    post:
      tags:
        - user
      security:
        - client: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                  description: 產品ID
                  example: 123
      responses:
        '200':
          description: 成功

  /client/wishlist/{wishId}:
    delete:
      tags:
        - user
      security:
        - client: []
      parameters:
        - in: path
          name: wishId
          schema:
            type: number
          required: true
          example: 123
      responses:
        '200':
          description: 成功

  /client/orders:
    get:
      tags:
        - user
      security:
        - client: []
      responses:
        '200':
          description: 成功

  # ==================
  # cart
  # ==================

  /cart/compute:
    post:
      tags:
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  description: 購物車內容
                  example:
                    - product_id: 1
                      qty: 2
                      sku: '96062623'
      responses:
        '200':
          description: 成功

  /cart/checkout:
    post:
      tags:
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_name:
                  type: string
                  description: 購買人
                  example: '老高'
                customer_country:
                  type: string
                  description: 帳單區域
                  example: '香港'
                customer_phone:
                  type: string
                  description: 帳單電話
                  example: '0900123123'
                customer_address:
                  type: string
                  description: 帳單地址
                  example: '九龍'
                customer_city:
                  type: string
                  description: 帳單城市
                  example: '九龍'
                customer_zip:
                  type: string
                  description: 帳單區碼
                  example: '123'
                customer_email:
                  type: string
                  description: 帳單郵件
                  example: 'zzz@nextgen.com'
                customer_state:
                  type: string
                  description: 帳單州
                  example: '九龍'
                shipping_name:
                  type: string
                  description: 取貨人
                  example: '茉莉'
                shipping_country:
                  type: string
                  description: 送達城市
                  example: '香港'
                shipping_phone:
                  type: string
                  description: 送達電話
                  example: '0900123123'
                shipping_address:
                  type: string
                  description: 送達地址
                  example: '新界'
                shipping_city:
                  type: string
                  description: 送達城市
                  example: '新界'
                shipping_zip:
                  type: string
                  description: 送達區碼
                  example: '123'
                shipping_email:
                  type: string
                  description: 送達郵件
                  example: 'aaa@nextgen.hk.com'
                shipping_state:
                  type: string
                  description: 送達州
                  example: '新界'
                order_note:
                  type: string
                  description: 訂單備註
                  example: '加辣'
                pickup_country:
                  type: string
                  description: 自取點城市
                  example: '香港'
                pickup_state:
                  type: string
                  description: 自取點州
                  example: '新界'
                shippingType:
                  type: number
                  description: 外送(1)或是自取點(2)
                  example: 1
                  enum:
                    - 1
                    - 2
                items:
                  type: array
                  description: 購物車內容
                  example:
                    - product_id: 1
                      qty: 2
                      sku: '96062623'
      responses:
        '200':
          description: 成功

  # ==================
  # orders
  # ==================

  /orders/{orderNumber}:
    get:
      tags:
        - orders
      parameters:
        - in: path
          name: orderNumber
          schema:
            type: string
          required: true
          example: Xk9Z1639460878
      responses:
        '200':
          description: 成功
        '404':
          description: 訂單不存在

  /orders/{orderNumber}/products:
    get:
      tags:
        - orders
      parameters:
        - in: path
          name: orderNumber
          schema:
            type: string
          required: true
          example: Xk9Z1639460878
      responses:
        '200':
          description: 成功
        '404':
          description: 訂單不存在

  /orders/{orderNumber}/pay/{paymentName}:
    post:
      tags:
        - orders
      parameters:
        - in: path
          name: orderNumber
          schema:
            type: string
          required: true
          example: Xk9Z1639460878
        - in: path
          name: paymentName
          schema:
            type: string
          required: true
          example: paypal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency:
                  type: string
                  description: 幣別
                  example: 'hkd'
      responses:
        '200':
          description: 成功
