openapi: 3.0.1

info:
  title: Main
  version: 1.0.0
  description: 這裡夾雜一些程式碼示範

# 這裡可以選擇網域
servers:
  - url: http://localhost:8000

components:
  # 定義一些 auth 認證的 token
  securitySchemes:
    token:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的token
  # 定義一些通用參數避免繁複定義
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:

  /users/{user}:
    get:
      summary: 這裡放簡易說明
      description: 這裡放複雜說明
      # 分類
      tags:
        - user
      # 有什麼變數
      parameters:
        # 可以透過開頭的 parameters 獲取通用的值
        - $ref: '#/components/parameters/language'
        # 個別定義各種參數
        - in: path
          name: user
          schema:
            type: string
          required: true
          example: '1'
      # 定義各種回傳
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: 使用者名稱
                    example: '小明'
    post:
      tags:
        - user
      # 需要怎樣的 token
      security:
        - token:
          # 權限說明(非標準)
          - 'users.read'
      parameters:
        # 個別定義各種參數
        - in: path
          name: user
          schema:
            type: string
          required: true
          example: '1'
      # 可以詳細定義 body
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 標題
                  example: 'hi...'
      responses:
        '200':
          description: 成功