openapi: 3.0.1

info:
  title: 配藥系統
  version: 1.0.0

servers:
  - url: https://medicine.nextgen.com.hk/api

components:
  parameters:
    page:
      in: query
      name: page
      schema:
        type: number
      required: true
      example: 1
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:
  /users-permissions/auth/login:
    post:
      summary: 員工登錄帳號
      description: 員工登錄帳號
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email
                  example: 'hi...'
                password:
                  type: string
                  description: 密碼
                  example: 'hi...'
      responses:
        '200':
          description: 成功
