openapi: 3.0.1

info:
  title: 配藥系統
  version: 1.0.0

servers:
  - url: https://medicine.nextgen.com.hk/api

components:
  parameters:
    page:
      in: query
      name: pagination[page]
      schema:
        type: number
      required: true
      example: 1
    prepage:
      in: query
      name: pagination[pageSize]
      schema:
        type: number
      required: true
      example: 100
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:

  # ====================
  #
  # Auth
  #

  /users-permissions/auth/login:
    post:
      summary: 員工登錄帳號
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email
                  example: 'pharmacist@nextgen.com.hk'
                password:
                  type: string
                  description: 密碼
                  example: 'nextgen123'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: number
                          username:
                            type: string
                          email:
                            type: string
                          provider:
                            type: string
                          confirmed:
                            type: boolean
                          blocked:
                            type: boolean
                          createdAt:
                            type: string
                          updatedAt:
                            type: string
                          memo:
                            type: string
                          level:
                            type: string
                          startedAt:
                            type: string
                          finishedAt:
                            type: string
                          isPharmacist:
                            type: boolean
                          store:
                            type: object
                            properties:
                              id:
                                type: number
                              nameCn:
                                type: string
                              nameEn:
                                type: string
                              tel:
                                type: string
                              address:
                                type: string
                              district:
                                type: string
                              rxNo:
                                type: string
                              createdAt:
                                type: string
                              updatedAt:
                                type: string
                              publishedAt:
                                type: string

  # ====================
  #
  # dosage
  #

  /dosage-forms:
    get:
      summary: 獲取藥物使用方法
      tags:
        - dosage
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/prepage'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        attributes:
                          type: object
                          properties:
                            key:
                              type: string
                            createdAt:
                              type: string
                            updatedAt:
                              type: string
                            publishedAt:
                              type: string
                  meta:
                    type: object
                    properties:
                      pagination:
                        type: object
                        properties:
                          page:
                            type: number
                          pageSize:
                            type: number
                          pageCount:
                            type: number
                          total:
                            type: number

  # ====================
  #
  # cautions
  #

  /cautions:
    get:
      summary: 獲取注意事項
      tags:
        - cautions
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/prepage'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        key:
                          type: string
                        value:
                          type: string
                  meta:
                    type: object
                    properties:
                      page:
                        type: number
                      perPage:
                        type: number
                      pageCount:
                        type: number
                      totalCount:
                        type: number

  # ====================
  #
  # hospitals
  #

  /hospitals:
    get:
      summary: 獲取醫院列表
      tags:
        - hospitals
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/prepage'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        institution_tc:
                          type: string
                        address_tc:
                          type: string
                        cluster_tc:
                          type: string
                        latitude:
                          type: number
                        longitude:
                          type: number
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                        institution_eng:
                          type: string
                        locale:
                          type: string
                        type:
                          type: object
                        key:
                          type: string
                  meta:
                    type: object
                    properties:
                      page:
                        type: number
                      perPage:
                        type: number
                      pageCount:
                        type: number
                      totalCount:
                        type: number

  # ====================
  #
  # drugs
  #

  /drugs/{drugId}:
    get:
      summary: 獲取指定藥品
      tags:
        - drug
      parameters:
        - name: drugId
          in: path
          description: 藥品id
          required: true
          example: 6595
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  permitNo:
                    type: string
                  productName_zh:
                    type: string
                  productName:
                    type: string
                  indication:
                    type: string
                  registration_date:
                    type: string
                  precaution:
                    type: string
                  side_effect:
                    type: string
                  regCertHolderName:
                    type: string
                  regCertHolderAddress:
                    type: string
                  regCertHolderCountry:
                    type: string
                  legal_classification:
                    type: string
                  sale_requirement:
                    type: string
                  ingredients:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      description:
                        type: string
                  packages:
                    type: array
                    items:
                      type: object
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        url:
                          type: string