openapi: 3.0.1

info:
  title: 配藥系統
  version: 1.0.0

servers:
  - url: https://medicine.nextgen.com.hk/api
    description: Staging server
  - url: http://0.0.0.0:1337/api
    description: local server

components:
  securitySchemes:
    client_token:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的 token, Bearer xxx
  parameters:
    page:
      in: query
      name: page
      schema:
        type: number
      required: true
      example: 1
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:

  # ====================
  #
  # Auth
  #

  /users-permissions/auth/login:
    post:
      summary: 員工登錄帳號
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email
                  example: 'pharmacist@nextgen.com.hk'
                password:
                  type: string
                  description: 密碼
                  example: 'nextgen123'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: number
                      username:
                        type: string
                      email:
                        type: string
                      provider:
                        type: string
                      confirmed:
                        type: boolean
                      blocked:
                        type: boolean
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      memo:
                        type: string
                      level:
                        type: string
                      startedAt:
                        type: string
                      finishedAt:
                        type: string
                      isPharmacist:
                        type: boolean
                      store:
                        type: object
                        properties:
                          id:
                            type: number
                          nanmeCn:
                            type: string
                          ameEn:
                            type: string
                          tel:
                            type: string
                          address:
                            type: string
                          district:
                            type: string
                          rxNo:
                            type: string
                          createdAt:
                            type: string
                          updatedAt:
                            type: string
                          publishedAt:
                            type: string


  # ====================
  #
  # customer
  #
  /customers:
    get:
      summary: 客人搜尋
      tags:
        - customers
      security:
        - client_token: []
      parameters:
        - in: query
          name: expand
          schema:
            type: string
          description: 擴展內容
          example: 'store,allergy'
        - in: query
          name: email
          schema:
            type: string
          description: 電子郵件
          example: 'pharmacist@nextgen.com.hk'
        - in: query
          name: mobile
          schema:
            type: string
          description: 電話號碼
          example: '1222'
        - in: query
          name: account_no
          schema:
            type: string
          description: 身份識別碼
          example: 'a1234567'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        uuid:
                          type: string
                        gender:
                          type: string
                        address:
                          type: string
                        email:
                          type: string
                        birthday:
                          type: string
                        name:
                          type: string
                        mobile:
                          type: string
                        accountNo:
                          type: string
                        drugTaboo:
                          type: string
                        store:
                          type: object
                          properties:
                            rxNo:
                              type: string
                            nameCn:
                              type: string
                            nameEn:
                              type: string
                            district:
                              type: string
                  meta:
                    type: object
                    properties:
                      page:
                        type: number
                      perPage:
                        type: number
                      pageCount:
                        type: number
                      totalCount:
                        type: number

    post:
      summary: 新建客人
      security:
        - client_token: []
      tags:
        - customers
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              
              properties:
                accountNo:
                  type: string
                  description: 身份識別碼
                  example: 'a1234567'
                name:
                  type: string
                  description: 顧客名稱
                  example: '顧客名稱'
                gender:
                  type: string
                  description: 性別
                  example: 'F'
                birthday:
                  type: string
                  description: 生日
                  example: '2021-01-01'
                address:
                  type: string
                  description: 地址
                  example: '大安區'
                email:
                  type: string
                  description: 電子郵件
                  example: 'pharmacist@nextgen.com.hk'
                mobile:
                  type: string
                  description: 聯絡電話
                  example: '12345'
                drugTaboo:
                  type: string
                  description: 禁忌
                  example: '特定藥品禁忌'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      gender:
                        type: string
                      address:
                        type: string
                      email:
                        type: string
                      birthday:
                        type: string
                      name:
                        type: string
                      mobile:
                        type: string
                      accountNo:
                        type: string
                      drugTaboo:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      uuid:
                        type: string
  /customers/{uuid}:
    put:
      summary: 修改客人資訊
      tags:
        - customers
      security:
        - client_token: []
      parameters:
        - name: uuid
          in: path
          description: 客人唯一識別碼
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              
              properties:
                accountNo:
                  type: string
                  description: 身份識別碼 
                  example: 'a1234567'
                name:
                  type: string
                  description: 顧客名稱
                  example: '顧客名稱'
                gender:
                  type: string
                  description: 性別
                  example: 'F'
                birthday:
                  type: string
                  description: 生日
                  example: '2021-01-01'
                address:
                  type: string
                  description: 地址
                  example: '大安區'
                email:
                  type: string
                  description: 電子郵件
                  example: 'pharmacist@nextgen.com.hk'
                mobile:
                  type: string
                  description: 聯絡電話
                  example: '12345'
                drugTaboo:
                  type: string
                  description: 禁忌
                  example: '特定藥品禁忌'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      gender:
                        type: string
                      address:
                        type: string
                      email:
                        type: string
                      birthday:
                        type: string
                      name:
                        type: string
                      mobile:
                        type: string
                      accountNo:
                        type: string
                      drugTaboo:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      uuid:
                        type: string


  # ====================
  #
  # order
  #

  /orders:
    post:
      summary: 新建訂單
      security:
        - client_token: []
      tags:
        - orders
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                customerUuid:
                  type: string
                  description:  顧客身份 uuid
                  example: 'c764f34b-dd29-454d-9fa0-db9a08e04607'
                signAt:
                  type: string
                  description: 生日
                  example: '2021-01-01'
                hospital:
                  type: string
                  description: 開藥醫院 id
                  example: '334'
                doctorName:
                  type: string
                  description: 開藥醫生
                  example: '醫生名稱'
                prescriptionSignMessage:
                  type: string
                  description: 處方簽症狀
                  example: '治療發燒、喉嚨痛'
                drug:
                  type: array
                  items:
                    type: integer
                  description: 藥品id
                  example: ['6595', '6597']
                day:
                  type: array
                  items:
                    type: integer
                  description: 用藥天數
                  example: ['3','3']
                frequency:
                  type: array
                  items:
                    type: string
                  description: 用藥頻率
                  example: ['take_morning_and_night','take_after_meals']
                usage:
                  type: array
                  items:
                    type: string
                  description: 藥品使用方式
                  example: ['oral','external']
                total:
                  type: array
                  items:
                    type: integer
                  description: 藥品數量
                  example: [6,9]
                dosageForm:
                  type: array
                  items:
                    type: string
                  description: 藥劑類型
                  example: ['tablet', 'capsule']
                caution:
                  type: array
                  items:
                    type: string
                  description: 警告
                  example: ['', '服用時禁止空腹']
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      signAt:
                        type: string
                      doctorName:
                        type: string
                      prescriptionSignMessage:
                        type: object
                      hospitalName:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      orderNo:
                        type: string

  /orders/{orderNo}:
    put:
      summary: 修改訂單
      security:
        - client_token: []
      parameters:
        - name: orderNo
          in: path
          description: 訂單唯一識別碼
          required: true
          schema:
            type: string
      tags:
        - orders
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                customerUuid:
                  type: string
                  description:  顧客身份 uuid
                  example: 'c764f34b-dd29-454d-9fa0-db9a08e04607'
                signAt:
                  type: string
                  description: 生日
                  example: '2021-01-01'
                hospital:
                  type: string
                  description: 開藥醫院 id
                  example: '334'
                doctorName:
                  type: string
                  description: 開藥醫生
                  example: '醫生名稱'
                prescriptionSignMessage:
                  type: string
                  description: 處方簽症狀
                  example: '治療發燒、喉嚨痛'
                drug:
                  type: array
                  items:
                    type: integer
                  description: 藥品id
                  example: ['6595', '6597']
                day:
                  type: array
                  items:
                    type: integer
                  description: 用藥天數
                  example: ['3','3']
                frequency:
                  type: array
                  items:
                    type: string
                  description: 用藥頻率
                  example: ['take_morning_and_night','take_after_meals']
                usage:
                  type: array
                  items:
                    type: string
                  description: 藥品使用方式
                  example: ['oral','external']
                total:
                  type: array
                  items:
                    type: integer
                  description: 藥品數量
                  example: [6,9]
                dosageForm:
                  type: array
                  items:
                    type: string
                  description: 藥劑類型
                  example: ['tablet', 'capsule']
                caution:
                  type: array
                  items:
                    type: string
                  description: 警告
                  example: ['', '服用時禁止空腹']
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      signAt:
                        type: string
                      doctorName:
                        type: string
                      prescriptionSignMessage:
                        type: object
                      hospitalName:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      orderNo:
                        type: string

  # ====================
  #
  # drug
  #
  /dosage-forms:
    get:
      summary: 搜尋藥劑類型
      tags:
        - drug
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        key:
                          type: string
                        usage:
                          type: string
                        unit:
                          type: string
                  meta:
                    type: object
                    properties:
                      page:
                        type: number
                      perPage:
                        type: number
                      pageCount:
                        type: number
                      totalCount:
                        type: number

  /drugs/frequencies:
    get:
      summary: 藥品使用頻率(每天)
      tags:
        - drug
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string

  /drugs/usages:
    get:
      summary: 藥劑使用方式
      tags:
        - drug
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
