openapi: 3.0.1

info:
  title: POS原生相關API
  version: 1.0.0
  description: POS原生相關API

servers:
  - url: http://localhost:8000/project/public
  - url: https://erp-dev.cloudsatlas.com.hk/public

components:
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'   
  schemas:
    CustomersResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: number
            description: 客戶ID
          text:
            type: string
            description: 客戶名稱
          mobile:
            type: string
            description: 手機
          address_line_1:
            type: string
          address_line_2:
            type: string
          city:
            type: string
          state:
            type: string
          country:
            type: string
          zip_code:
            type: string
          shipping_address:
            type: string
            description: 寄件地址
          pay_term_number:
            type: string
          pay_term_type:
            type: string
          balance:
            type: string
          supplier_business_name:
            type: string
          discount_percent:
            type: string
          price_calculation_type:
            type: string
          selling_price_group_id:
            type: integer
          shipping_custom_field_details:
            type: string
          is_export:
            type: integer
          export_custom_field_1:
            type: string
          export_custom_field_2:
            type: string
          export_custom_field_3:
            type: string
          export_custom_field_4:
            type: string
          export_custom_field_5:
            type: string
          export_custom_field_6:
            type: string
          passportNo:
            type: string
          passportName:
            type: string
          HKID:
            type: integer
          prefix:
            type: string
          email:
            type: string
            description: 信箱
          last_name:
            type: string
            description: 姓
          first_name:
            type: string
            description: 名
    ProductListResponse:
      type: array
      items:
        type: object
        properties:
          product_id:
            type: number
            description: 產品ID
          name:
            type: string
            description: 產品名稱
          type:
            type: string
            description: 產品類型
          enable_stock:
            type: integer
            description: 是否啟用庫存
          variation_id:
            type: integer
            description: 規格ID
          variation:
            type: string
            description: 規格名稱
          qty_available:
            type: number
            description: 庫存數量
          selling_price:
            type: number
            description: 售價
          sub_sku:
            type: string
            description: Sub SKU
          unit:
            type: string
            description: 單位
          category_id:
            type: integer
            description: 分類ID
          purchase_line_id:
            type: integer
            description: Purchase Line ID
          lot_number:
            type: string
            description: 批號
          image_url:
            type: string
            description: 圖片URL
          
paths:
  /contacts/customers:
    get:
      summary: 取得客戶列表
      description: 取得客戶列表
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: 過濾條件

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersResponse'
              example:
                id: 1
                text: "Walk-In Customer (CO0001)"
                mobile: "0000"
                address_line_1: null
                address_line_2: null
                city: null
                state: null
                country: null
                zip_code: null
                shipping_address: null
                pay_term_number: null
                pay_term_type: null
                balance: "0.0000"
                supplier_business_name: null
                discount_percent: null
                price_calculation_type: null
                selling_price_group_id: null
                shipping_custom_field_details: null
                is_export: 0
                export_custom_field_1: null
                export_custom_field_2: null
                export_custom_field_3: null
                export_custom_field_4: null
                export_custom_field_5: null
                export_custom_field_6: null
                passportNo: null
                passportName: null
                HKID: null
                prefix: null
                email: null
                last_name: null
                first_name: "Walk-In Customer"

  /products/list:
    get:
      summary: 取得產品列表
      description: 取得產品列表
      parameters:
        - in: query
          name: price_group
          schema:
            type: integer
          description: 價格群組ID
        - in: query
          name: location_id
          schema:
            type: integer
          description: 分店ID
        - in: query
          name: term
          schema:
            type: string
          description: 搜尋條件
        - in: query
          name: not_for_selling
          schema:
            type: integer
          description: 是否為非賣品
        - in: query
          name: search_fields
          schema:
            type: array
          description: 搜尋欄位

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'
              example:       
                - product_id: 76
                  name: "滴眼液"
                  type: "medicine"
                  enable_stock: 1
                  variation_id: 127
                  variation: "顆粒 (粒)"
                  qty_available: "2123.0000"
                  selling_price: "125.0000"
                  sub_sku: "0076-1"
                  unit: "粒"
                  category_id: null
                  purchase_line_id: 84
                  lot_number: "Batch111"
                  image_url: "http://localhost:8000/project/public/img/default.png"
                - product_id: 70
                  name: "可樂"
                  type: "single"
                  enable_stock: 1
                  variation_id: 119
                  variation: "DUMMY"
                  qty_available: "2059.0000"
                  selling_price: "125.0000"
                  sub_sku: "0070"
                  unit: "Pc(s)"
                  category_id: 5
                  purchase_line_id: 70
                  lot_number: "batch111"
                  image_url: "http://localhost:8000/project/public/img/default.png"
  
  /sells/pos/get_product_row/{variation_id}/{location_id}:
    get:
      summary: 取得單一產品規格資訊
      description: 取得單一產品規格資訊
      parameters:
        - in: path
          name: variation_id
          required: true
          schema:
            type: integer
          description: 規格ID
        - in: path
          name: location_id
          required: true
          schema:
            type: integer
          description: 分店ID
        - in: query
          name: product_row
          schema:
            type: integer
        - in: query
          name: customer_id
          schema:
            type: integer
          description: 客戶ID
        - in: query
          name: is_direct_sell
          schema:
            type: boolean
            default: false
          description: 是否為直接銷售
        - in: query
          name: price_group
          schema:
            type: integer
          description: 價格群組ID
        - in: query
          name: purchase_line_id
          schema:
            type: integer
          description: Purchase Line ID
        - in: query
          name: weighing_scale_barcode
          schema:
            type: integer
        - in: query
          name: quantity
          schema:
            type: integer
            default: 1
          description: 數量
        - in: query
          name: is_sales_order
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  enable_sr_no:
                    type: integer
                  html_content:
                    type: string
                    description: HTML
                  success:
                    type: boolean
                    description: 是否成功
              example:
                enable_sr_no: 0
                html_content: <tr class="product_row" data-row_index="2" >...</tr>
                success: true
              