openapi: 3.0.1

info:
  title: SCRM FOR SSO API
  version: 1.0.0

servers:
  - url: https://scrm-api-dev.cloudsatlas.com.hk/api
    description: dev server
  - url: http://localhost:11338/api

components:
  securitySchemes:
    client:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的 token, Bearer xxx

paths:

  # ====================
  #
  # Auth
  #
  /auth/login :
    post:
      summary: scrm系統登入
      description: scrm系統登入
      tags: 
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: jintian
                  description: 登入account
                password:
                  type: string
                  example: "1234567890"
                  description: 登入密碼
                appId:
                  type: string
                  example: 6f046e51-fd54-4749-b3ac-68e8a37f5e86
                  description: 屬於哪一間公司
              required:
                - username
                - password
                - appId

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: number
                          email:
                            type: string
                          displayName:
                            type: string
                          username:
                            type: string
                          confirmed:
                            type: boolean
                          phone:
                            type: string
                          notes:
                            type: string
                          blocked:
                            type: boolean
                          avatar:
                            type: string
                          role:
                            type: string
                          company:
                            type: number
                      platform:
                          type: array
                          description: 該使用者所屬公司有開啟的社群平台帳號（superadmin不會有）
                          items:
                            type: object
                            properties:
                              platform:
                                type: string
                              account:
                                type: object
                              enable:
                                type: boolean
  /auth/cloudsatlas :
    post:
      summary: nss登入
      description: nss登入
      tags: 
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                crm-token:
                  type: string
                companyUuid:
                  type: string

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: number
                          blocked:
                            type: boolean
                          confirmed:
                            type: boolean
                          createdAt:
                            type: string
                          email:
                            type: string
                          updatedAt:
                            type: string
                          username:
                            type: string
                          displayName:
                            nullable: true
                            type: string
                          provider:
                            nullable: true
                            type: string
                          avatar:
                            nullable: true
                            type: string
                          role:
                            type: string
  /auth/companies :
    post:
      summary: 登入取得companies appId
      description: 登入取得companies appId
      tags: 
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: jintian
                  description: 登入account
                password:
                  type: string
                  example: 1234567890
                  description: 登入密碼
                channel:
                  type: string
                  description: 哪個品牌
                  enum:
                    - cas
                    - nextgen
              required:
                - username
                - password

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string

  /auth/sso/verify:
    post:
      summary: 第三方註冊登入
      description: 前端提供token及provider供後端驗證確認後進行註冊並交換token給前端
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                  description: 從SSO系統拿到的token
                appId:
                  type: string
                  example: 6f046e51-fd54-4749-b3ac-68e8a37f5e86
                  description: 個別廠商的uuid
              required:
                - token
                - appId

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: number
                          email:
                            type: string
                          displayName:
                            type: string
                          username:
                            type: string
                          confirmed:
                            type: boolean
                          phone:
                            type: string
                          notes:
                            type: string
                          blocked:
                            type: boolean
                          avatar:
                            type: string
                          role:
                            type: string
                          company:
                            type: number
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  伺服器錯誤
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  驗證錯誤                              
  
  /auth/forgot-password :
    post:
      summary: 忘記密碼
      description: 忘記密碼
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: account
                email:
                  type: string
                  description: email  
                appId:
                  type: string
                  example: 6f046e51-fd54-4749-b3ac-68e8a37f5e86
                  description: 個別廠商的uuid
              required:
                - username
                - email
                - appId
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  /auth/reset-password :
    post:
      summary: 重設密碼
      description: 重設密碼
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: strapi產的code,接在url中的query
                password:
                  type: string
                  description: 重設的密碼
                passwordConfirmation:
                  type: string
                  description: 重設密碼確認
              required:
                - code
                - password
                - passwordConfirmation
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

