openapi: 3.0.1

info:
  title: SCRM FOR SSO API
  version: 1.0.0

servers:
  - url: https://scrm-api-dev.cloudsatlas.com.hk/api
    description: dev server

components:
  securitySchemes:
    client:
      in: header
      type: apiKey
      name: Authorization
      description: 驗證需要的 token, Bearer xxx

paths:

  # ====================
  #
  # Auth
  #
  /auth/verifySSO:
    post:
      summary: 第三方註冊登入
      description: 前端提供token及provider供後端驗證確認後進行註冊並交換token給前端
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                  description: 從SSO系統拿到的token
                appId:
                  type: string
                  example: 77046e51-fd54-4749-b3ac-68e8a37f5e86
                  description: 個別廠商的uuid
              required:
                - token
                - appId

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  伺服器錯誤
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  驗證錯誤                              
  

  # ====================
  #
  # User
  #

  /users:
    get: 
      summary: 取得所有與登入者同company的客服資料
      description: 取得所有與登入者同company的客服資料
      tags:
        - users
      security:
        - client: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        username:
                          type: string
                        displayName:
                          type: string
                        avatar:
                          type: string
    post:
      summary: 創建客服（管理者權限才可使用）
      description: 管理者創建新客服
      tags:
        - users
      security:
        - client: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 客服帳號名稱
                email:
                  type: string
                  example: 123@123.com
                  description: 客服信箱
                password:
                  type: string
                  example: 123456789
                  description: 客服密碼
                confirmPassword:
                  type: string
                  example: 123456789
                  description: 客服密碼
                displayName:
                  type: string
                  example: TJ
                  description: 客服前台顯示名稱  
                avatar  :  
                  type: string
                  format: binary
                  description: 客服大頭貼                                                    
              required:
                - username
                - email
                - password
                - confirmPassword

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  username:
                    type: string
                  email:
                    type: string
                  provider:
                    type: string
                  confirmed:
                    type: boolean
                  blocked:
                    type: boolean
                  displayName:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                  phone:
                    type: object
                  notes:
                    type: object
                  isDeleted:
                    type: boolean
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  伺服器錯誤
        '400':
          description: 失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example:  建立失敗                              
  

  /users/{id}:
   get:
      summary: 查詢特定客服資料
      description: 查詢特定客服資料
      tags:
        - users
      security:
        - client: []
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
          example: 1

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      username:
                        type: string
                      email:
                        type: string
                      provider:
                        type: string
                      password:
                        type: string
                      resetPasswordToken:
                        type: object
                      confirmationToken:
                        type: object
                      confirmed:
                        type: boolean
                      blocked:
                        type: boolean
                      displayName:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      phone:
                        type: object
                      notes:
                        type: object
                      isDeleted:
                        type: boolean

  /users/me:
   get:
      summary: 查詢客服資料
      description: 查詢客服資料
      tags:
        - users
      security:
        - client: []

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            displayName:
                              type: string
                            avatar:
                              type: string

