openapi: 3.0.1

info:
  title: Main
  version: 1.0.0
  description: 這裡夾雜一些程式碼示範

servers:
  - url: http://localhost:8000
  - url: https://pos.cloudsatlas.com.hk/public/api

tags:
  - name: Business
    description: Operations about business
  - name: Transaction
    description: Operations about transaction
  - name: Product
    description: Operations about product
  - name: user
    description: Operations about user

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 驗證需要的token
  parameters:
    language:
      in: header
      name: accept-language
      schema:
        type: string
      required: false
      example: 'en'

paths:
  /info:
    get:
      summary: Business Location 詳細資訊
      description: 會列出 Location 的詳細資訊
      tags:
        - Business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      mobile:
                        type: string
                      country:
                        type: string
                      state:
                        type: string
                      city:
                        type: string
                      zip_code:
                        type: string

  /on-duty:
    get:
      summary: 值班人員
      description: 取得值班店員與值班藥師資訊
      tags:
        - Business
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user_id:
                        type: number
                      user_name:
                        type: string
                      pharmacist_id:
                        type: number
                      pharmacist_name:
                        type: string


  /transactions:
    get:
      summary: 交易清單
      description: 取得交易清單
      tags:
        - Transaction
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        pharmacist_name:
                          type: string
                        prescription_sign_message:
                          type: string
                        username:
                          type: string
                        contact_name:
                          type: string
                        created_at:
                          type: string
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number

  /transactions/{id}:
    get:
      summary: 單一交易
      description: 取得單一交易資訊
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of transaction to return
          required: true
          example: 126
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      created_at:
                        type: string
                      contact_id:
                        type: number
                      contact_dob:
                        type: string
                      contact_name:
                        type: string
                      total_amount:
                        type: string


  /transactions/{id}/products:
    get:
      summary: 交易表裡的產品清單
      description: 取得交易表裡的產品清單
      tags:
        - Transaction
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of transaction to return
          required: true
          example: 126
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        sell_id:
                          type: number
                        quantity:
                          type: number
                        price:
                          type: string
                        usage_id:
                          type: number
                        product_id:
                          type: number
                        days:
                          type: number
                        total:
                          type: number
                        dosage:
                          type: number
                        frequency:
                          type: number
                        cautions:
                          type: array
                          items:
                            type: object
                        custom_caution:
                          type: string
                        dosage_form:
                          type: string
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number

  /products:
    get:
      summary: 產品清單
      description: "取得產品清單"
      tags:
        - Product
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        sku:
                          type: string
                        name:
                          type: string
                        qty_available:
                          type: number
                        alert_quantity:
                          type: string
                        default_sell_price:
                          type: string
                        product_custom_field1:
                          type: string
                        product_custom_field2:
                          type: string
                        product_custom_field3:
                          type: string
                        product_custom_field4:
                          type: string
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: number
                      from:
                        type: number
                      last_page:
                        type: number
                      path:
                        type: string
                      per_page:
                        type: number
                      to:
                        type: number
                      total:
                        type: number


  /products/{id}:
    get:
      summary: '取得單一產品'
      description: 取得單一產品詳細資訊
      tags:
        - Product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      sku:
                        type: string
                      name:
                        type: string
                      unit_id:
                        type: number
                      qty_available:
                        type: number
                      alert_quantity:
                        type: string
                      unit_short_name:
                        type: string
                      default_sell_price:
                        type: string
                      product_custom_field1:
                        type: string
                      product_custom_field2:
                        type: string
                      product_custom_field3:
                        type: string
                      product_custom_field4:
                        type: string
